apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  RDS_ENDPOINT: <base64 endpoint>
  RDS_USERNAME: <base64 username>
  RDS_PASSWORD: <base64 password>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: projectaws/pythonappkuberenetes
        ports:
        - containerPort: 5000
        env:
        - name: RDS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: RDS_ENDPOINT
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: RDS_USERNAME
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: RDS_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
