name: Build and push docker image
on:
  push:
    branches: [AppParameterStore]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: login to the docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Building the docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/githubactions:latest aws-rds-DB/db-app
      - name: push docker image to docker hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
