name: Build and push docker image
on:
  push:
    branches: [AppParameterStore]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: login to the docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Building the docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/githubactions:latest db-app
      - name: push docker image to docker hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/githubactions:latest
  deployment:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/githubactions:latest
            docker stop app-container || true
            docker rm app-container || true
            docker run -d --name app-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/githubactions:latest
